export const COUNTRY_CODES: Record<string, string> = {
  // Américas
  "Brasil": "BR",
  "Argentina": "AR",
  "Chile": "CL",
  "Uruguai": "UY",
  "Paraguai": "PY",
  "Bolívia": "BO",
  "Peru": "PE",
  "Equador": "EC",
  "Colômbia": "CO",
  "Venezuela": "VE",
  "Guiana": "GY",
  "Suriname": "SR",
  "Guiana Francesa": "GF",

  "Canadá": "CA",
  "Estados Unidos": "US",
  "México": "MX",

  "Guatemala": "GT",
  "Belize": "BZ",
  "Honduras": "HN",
  "El Salvador": "SV",
  "Nicarágua": "NI",
  "Costa Rica": "CR",
  "Panamá": "PA",

  "Cuba": "CU",
  "Haiti": "HT",
  "Jamaica": "JM",
  "República Dominicana": "DO",
  "Bahamas": "BS",
  "Barbados": "BB",
  "Trinidad e Tobago": "TT",

  // Europa
  "Portugal": "PT",
  "Espanha": "ES",
  "França": "FR",
  "Alemanha": "DE",
  "Itália": "IT",
  "Suíça": "CH",
  "Áustria": "AT",
  "Bélgica": "BE",
  "Países Baixos": "NL",
  "Luxemburgo": "LU",

  "Inglaterra": "GB",
  "Reino Unido": "GB",
  "Escócia": "GB",
  "País de Gales": "GB",
  "Irlanda": "IE",

  "Dinamarca": "DK",
  "Noruega": "NO",
  "Suécia": "SE",
  "Finlândia": "FI",
  "Islândia": "IS",

  "Polônia": "PL",
  "República Tcheca": "CZ",
  "Eslováquia": "SK",
  "Hungria": "HU",

  "Grécia": "GR",
  "Turquia": "TR",
  "Chipre": "CY",

  "Croácia": "HR",
  "Eslovênia": "SI",
  "Sérvia": "RS",
  "Montenegro": "ME",
  "Albânia": "AL",
  "Macedônia do Norte": "MK",
  "Bulgária": "BG",
  "Romênia": "RO",

  "Ucrânia": "UA",
  "Rússia": "RU",
  "Belarus": "BY",
  "Lituânia": "LT",
  "Letônia": "LV",
  "Estônia": "EE",

  // África
  "Egito": "EG",
  "Marrocos": "MA",
  "Argélia": "DZ",
  "Tunísia": "TN",
  "Líbia": "LY",

  "África do Sul": "ZA",
  "Angola": "AO",
  "Moçambique": "MZ",
  "Namíbia": "NA",
  "Botsuana": "BW",
  "Zimbábue": "ZW",
  "Zâmbia": "ZM",
  "Maláui": "MW",

  "Quênia": "KE",
  "Tanzânia": "TZ",
  "Uganda": "UG",
  "Ruanda": "RW",
  "Burundi": "BI",

  "Gana": "GH",
  "Nigéria": "NG",
  "Camarões": "CM",
  "Senegal": "SN",
  "Mali": "ML",
  "Costa do Marfim": "CI",

  // Ásia
  "China": "CN",
  "Japão": "JP",
  "Coreia do Sul": "KR",
  "Coreia do Norte": "KP",
  "Índia": "IN",
  "Paquistão": "PK",
  "Bangladesh": "BD",
  "Nepal": "NP",
  "Sri Lanka": "LK",

  "Tailândia": "TH",
  "Vietnã": "VN",
  "Camboja": "KH",
  "Laos": "LA",
  "Mianmar": "MM",
  "Malásia": "MY",
  "Cingapura": "SG",
  "Indonésia": "ID",
  "Filipinas": "PH",

  "Israel": "IL",
  "Arábia Saudita": "SA",
  "Emirados Árabes Unidos": "AE",
  "Catar": "QA",
  "Barein": "BH",
  "Omã": "OM",
  "Kuwait": "KW",
  "Jordânia": "JO",
  "Líbano": "LB",
  "Irã": "IR",
  "Iraque": "IQ",

  // Oceania
  "Austrália": "AU",
  "Nova Zelândia": "NZ",
  "Fiji": "FJ",
  "Papua-Nova Guiné": "PG",
  "Samoa": "WS",
  "Tonga": "TO",
};
